server.port=8082

spring.application.name=ms-carrito

spring.datasource.url=jdbc:mysql://localhost:3306/carrito?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

url.auth=http://localhost:8080/auth/usuarios/
url.catalogo=http://localhost:8081/catalogo/pizzas/


# Swagger / OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha

#abrir en http://localhost:8082/swagger-ui/index.html