server.port=8088

spring.application.name=ms-resenas

spring.datasource.url=jdbc:mysql://localhost:3306/resenas?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false

url.pedidos=http://localhost:8083/pedidos/
url.auth=http://localhost:8080/auth/usuarios/
url.notificaciones=http://localhost:8086/notificaciones/

# Swagger / OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha

#ver en http://localhost:8088/swagger-ui/index.html