# 1. PUERTO DEL MICROSERVICIO
server.port=8084

# 2. NOMBRE DE LA APLICACIÓN
spring.application.name=ms-inventario

# 3. CONEXIÓN A LARAGON
spring.datasource.url=jdbc:mysql://localhost:3306/inventario?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=

# 4. ESTRATEGIA DE HIBERNATE
spring.jpa.hibernate.ddl-auto=update

# 5. MOSTRAR SQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# 6. URLS DE OTROS MICROSERVICIOS (Aquí guardamos la conexión con el Catálogo)
ms-catalogo.url=http://localhost:8081/catalogo/