
server.port=8089


spring.application.name=ms-certificacion


spring.datasource.url=jdbc:mysql://localhost:3306/certificacion?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=


spring.jpa.hibernate.ddl-auto=update


spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


url.pedidos=http://localhost:8083/pedidos/
url.reparto=http://localhost:8087/reparto/